//! Check-level `kind = "missing"` ledger entries must exactly cover the
//! reference checks the port has not implemented.
//!
//! The reference check list is baked into `tests/data/reference-checks.txt`
//! (generated by `scripts/gen-reference-checks.py` from the pinned rpmlint
//! tree, so the test needs no reference checkout at runtime); the ported set
//! comes from the `check::build` match arms in `src/check.rs` -- the same
//! source-scanning shape as `check_registry.rs`, so the registry in code is
//! the authority, not a hand list. If a check is ported without its ledger
//! entry being removed, or an entry names a check the port already builds
//! (or the reference never had), this test fails.
//!
//! Finding-level `kind = "missing"` entries (e.g.
//! `logrotate-log-dir-not-packaged`) name a finding slug rather than a check
//! module and are out of scope here: only entries whose `check` names a
//! reference check module count toward the check-level set.

use std::collections::HashSet;
use std::path::PathBuf;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Reference check modules, from the generated data file.
fn reference_checks() -> HashSet<String> {
    let raw = std::fs::read_to_string(manifest_dir().join("tests/data/reference-checks.txt"))
        .expect("read tests/data/reference-checks.txt");
    raw.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

/// Checks `check::build` can construct: the `"Name" =>` match arms, keyed by
/// the exact Python module name.
fn ported_checks() -> HashSet<String> {
    let src =
        std::fs::read_to_string(manifest_dir().join("src/check.rs")).expect("read src/check.rs");
    let body = match src.find("pub fn build(") {
        Some(start) => {
            let rest = &src[start..];
            let end = rest.find("\n}\n").map(|i| i + 1).unwrap_or(rest.len());
            &rest[..end]
        }
        None => panic!("check::build not found"),
    };
    let mut names = HashSet::new();
    for line in body.lines() {
        // Match arms look like `"TagsCheck" => Some(Box::new(...))`; the
        // `_ => None` arm carries no string literal.
        let line = line.trim();
        if let Some(rest) = line.strip_prefix('"') {
            if let Some(end) = rest.find('"') {
                let name = &rest[..end];
                if rest[end + 1..].trim_start().starts_with("=>") {
                    names.insert(name.to_string());
                }
            }
        }
    }
    names
}

/// `check` values of the check-level `kind = "missing"` ledger entries:
/// entries whose `check` names a reference check module.
fn ledger_missing_checks(reference: &HashSet<String>) -> HashSet<String> {
    let raw = std::fs::read_to_string(manifest_dir().join("../../tests/parity/divergences.toml"))
        .expect("read tests/parity/divergences.toml");
    let parsed: toml::Value = toml::from_str(&raw).expect("ledger must parse as TOML");
    let divergences = parsed
        .get("divergence")
        .and_then(toml::Value::as_array)
        .unwrap_or_else(|| panic!("ledger has no [[divergence]] array"));
    divergences
        .iter()
        .filter_map(|v| v.as_table())
        .filter(|t| t.get("kind").and_then(toml::Value::as_str) == Some("missing"))
        .filter_map(|t| t.get("check").and_then(toml::Value::as_str))
        .filter(|check| reference.contains(*check))
        .map(str::to_string)
        .collect()
}

#[test]
fn missing_entries_exactly_cover_unported_checks() {
    let reference = reference_checks();
    assert!(
        !reference.is_empty(),
        "tests/data/reference-checks.txt is empty"
    );
    let ported = ported_checks();
    // The registry is keyed by the exact Python module name, so everything
    // it builds must be a reference check.
    let mut foreign: Vec<&String> = ported.difference(&reference).collect();
    foreign.sort();
    assert!(
        foreign.is_empty(),
        "check::build constructs checks the reference never had: {foreign:?}"
    );

    let missing = ledger_missing_checks(&reference);
    let expected: HashSet<String> = reference.difference(&ported).cloned().collect();

    let mut extra: Vec<&String> = missing.difference(&expected).collect();
    extra.sort();
    let mut absent: Vec<&String> = expected.difference(&missing).collect();
    absent.sort();
    assert!(
        extra.is_empty() && absent.is_empty(),
        "check-level kind=missing ledger entries drifted from \
         reference-minus-registry: entries with no matching unported check: \
         {extra:?}; unported checks with no entry: {absent:?}"
    );
}
