//! Dependency information, mirroring rpmlint's `DepInfo` and the
//! `stringToVersion`/`versionToString` helpers (`rpmlint/pkg.py`).

/// A dependency edge: name, raw `RPMSENSE_*` flags, and the parsed EVR.
///
/// rpmlint's `DepInfo` version part is a `(epoch, version, release)` tuple;
/// here it is three fields. `epoch` is an integer or `None`, `version`/
/// `release` strings or `None` (matching `stringToVersion`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DepInfo {
    pub name: String,
    pub flags: u32,
    pub epoch: Option<i64>,
    pub version: Option<String>,
    pub release: Option<String>,
}

impl DepInfo {
    /// The EVR in `[epoch:]version[-release]` form (rpmlint `versionToString`).
    pub fn evr_string(&self) -> String {
        version_to_string(self.epoch, self.version.as_deref(), self.release.as_deref())
    }
}

/// RPM `RPMSENSE_*` flags (`rpmds.h`); also synthesized for rich-dependency
/// leaf version constraints.
pub const RPMSENSE_LESS: u32 = 2;
pub const RPMSENSE_GREATER: u32 = 4;
pub const RPMSENSE_EQUAL: u32 = 8;
/// Set on header deps auto-generated by find-requires; the reference skips
/// these when seeding core requires (reference get_core_reqs).
pub const RPMSENSE_FIND_REQUIRES: u32 = 1 << 14;

impl DepInfo {
    /// The plain dependencies referenced by this entry.
    ///
    /// Rich `(a or b)` expressions (RPM >= 4.13) expand to their leaves; a
    /// plain name — with an optional RPM >= 4.16 `(qualifier)`, recorded
    /// but kept in the leaf name — yields one leaf carrying the header
    /// flags/EVR. The name stays literal (`rpmlib(CompressedFileNames)`,
    /// `qux(meta)`), exactly like the reference’s string matching; only
    /// the qualifier is additionally structured. Malformed input falls back
    /// to the raw name.
    pub fn leaves(&self) -> Vec<DepLeaf> {
        match parse_dep_expr(&self.name) {
            DepExpr::Simple {
                qualifier,
                flags,
                epoch,
                version,
                release,
                ..
            } => {
                // A header entry's flags/EVR describe a plain name; an
                // inline version constraint (only from rich-expression
                // terms) takes precedence when present.
                let (flags, epoch, version, release) = if version.is_some() || flags != 0 {
                    (flags, epoch, version, release)
                } else {
                    (
                        self.flags,
                        self.epoch,
                        self.version.clone(),
                        self.release.clone(),
                    )
                };
                vec![DepLeaf {
                    name: self.name.clone(),
                    qualifier,
                    flags,
                    epoch,
                    version,
                    release,
                }]
            }
            expr => expr.leaves(),
        }
    }

    /// Bare names referenced by this entry, for name-based analyses.
    pub fn leaf_names(&self) -> Vec<String> {
        self.leaves().iter().map(|l| l.name.clone()).collect()
    }
}

/// rpmlint's `stringToVersion`: parse `[epoch:]version[-release]`.
/// A non-numeric epoch is ignored; an empty version part becomes `None`.
pub fn string_to_version(s: &str) -> (Option<i64>, Option<String>, Option<String>) {
    if s.is_empty() {
        return (None, None, None);
    }
    let colon = s.find(':');
    let epoch = colon.and_then(|idx| s[..idx].parse::<i64>().ok());
    let i = colon.map_or(0, |idx| idx + 1);
    let rest = &s[i..];
    match rest.find('-') {
        Some(j) => {
            let version = &rest[..j];
            let release = &rest[j + 1..];
            (
                epoch,
                (!version.is_empty()).then(|| version.to_string()),
                Some(release.to_string()),
            )
        }
        None => (epoch, (!rest.is_empty()).then(|| rest.to_string()), None),
    }
}

/// rpmlint's `versionToString`: render an EVR tuple back to a string.
pub fn version_to_string(
    epoch: Option<i64>,
    version: Option<&str>,
    release: Option<&str>,
) -> String {
    let mut ret = String::new();
    if let Some(e) = epoch {
        ret.push_str(&format!("{e}:"));
    }
    if let Some(v) = version {
        ret.push_str(v);
        if let Some(r) = release.filter(|r| !r.is_empty()) {
            ret.push('-');
            ret.push_str(r);
        }
    }
    ret
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn string_to_version_matches_rpmlint() {
        assert_eq!(string_to_version(""), (None, None, None));
        assert_eq!(
            string_to_version("1.2.3"),
            (None, Some("1.2.3".to_string()), None)
        );
        assert_eq!(
            string_to_version("1.2.3-4"),
            (None, Some("1.2.3".to_string()), Some("4".to_string()))
        );
        assert_eq!(
            string_to_version("1:1.2.3-4"),
            (Some(1), Some("1.2.3".to_string()), Some("4".to_string()))
        );
        // garbage epoch is ignored
        assert_eq!(
            string_to_version("x:1.2.3"),
            (None, Some("1.2.3".to_string()), None)
        );
        // bare colon -> empty version part -> None
        assert_eq!(string_to_version(":"), (None, None, None));
        assert_eq!(string_to_version("1:"), (Some(1), None, None));
    }

    #[test]
    fn version_to_string_roundtrips() {
        assert_eq!(
            version_to_string(Some(1), Some("1.2.3"), Some("4")),
            "1:1.2.3-4"
        );
        assert_eq!(version_to_string(None, Some("1.2.3"), None), "1.2.3");
        assert_eq!(version_to_string(None, None, None), "");
    }
}

/// `rpmlint.pkg.parse_deps`: split a dependency line into `(name, version)`
/// pairs. The version is `Some` exactly when the dep is versioned (the
/// reference's `flags != 0`); only its presence is ever read (`unversioned`),
/// never the value.
/// Split a dep line on whitespace/commas, keeping parenthesized rich
/// expressions (`(a or b)`) as single tokens instead of shredding them into
/// plain-name pieces the way the reference does.
fn split_dep_tokens(line: &str) -> Vec<&str> {
    let mut tokens: Vec<&str> = Vec::new();
    let mut start: Option<usize> = None;
    let mut depth = 0u32;
    for (i, c) in line.char_indices() {
        match c {
            '(' => {
                start.get_or_insert(i);
                depth += 1;
            }
            ')' => {
                start.get_or_insert(i);
                depth = depth.saturating_sub(1);
            }
            _ if (c.is_whitespace() || c == ',') && depth == 0 => {
                if let Some(s) = start.take() {
                    tokens.push(&line[s..i]);
                }
            }
            _ => {
                start.get_or_insert(i);
            }
        }
    }
    if let Some(s) = start {
        tokens.push(&line[s..]);
    }
    tokens
}

/// First token of a dependency line, without tokenizing the rest of the line.
///
/// Same token boundaries as [`split_dep_tokens`], but the scan stops at the
/// end of the first token instead of allocating a `Vec` for the whole line.
/// The forbidden-controlchar check only ever examines this token, so the
/// comparison-operator fast path in the spec checks can probe it cheaply
/// when the raw line carries no comparison operator.
pub fn first_dep_token(line: &str) -> Option<&str> {
    let mut start: Option<usize> = None;
    let mut depth = 0u32;
    for (i, c) in line.char_indices() {
        match c {
            '(' => {
                start.get_or_insert(i);
                depth += 1;
            }
            ')' => {
                start.get_or_insert(i);
                depth = depth.saturating_sub(1);
            }
            _ if (c.is_whitespace() || c == ',') && depth == 0 => {
                if let Some(s) = start.take() {
                    return Some(&line[s..i]);
                }
            }
            _ => {
                start.get_or_insert(i);
            }
        }
    }
    start.map(|s| &line[s..])
}

pub fn parse_deps(line: &str) -> Vec<(String, Option<String>)> {
    let mut tokens: Vec<&str> = split_dep_tokens(line);
    // Drop a trailing line-continuation backslash from a multi-line macro
    // definition (`pkg.py:310-311`).
    if tokens.last().is_some_and(|t| *t == "\\") {
        tokens.pop();
    }

    let mut prcos = Vec::new();
    // The reference accumulates `prco` as [name], [name, flags],
    // [name, flags, evr]; only the name and "is versioned" survive here.
    let mut prco: Vec<String> = Vec::new();
    for token in tokens {
        match prco.len() {
            0 => prco.push(token.to_string()),
            1 => {
                if token.starts_with(['=', '<', '>']) {
                    prco.push(String::new());
                } else {
                    prcos.push((prco.pop().unwrap(), None));
                    prco.push(token.to_string());
                }
            }
            _ => {
                let name = prco[0].clone();
                prcos.push((name, Some(token.to_string())));
                prco.clear();
            }
        }
    }
    match prco.len() {
        // A dangling version operator (`Requires: foo >=`): versioned, but
        // the version token is missing. `Some` marks versioned-ness; the
        // value is never read.
        2 => prcos.push((prco[0].clone(), Some(String::new()))),
        1 => prcos.push((prco.pop().unwrap(), None)),
        _ => {}
    }
    prcos
}

/// `rpmlint.pkg.parse_deps` in full: split a dependency line into `DepInfo`s
/// (name, flags, EVR). Package-level tags carry separate flags/version arrays
/// (see `gather_deps`); this covers dep *lines* -- per-file `FILEREQUIRE` /
/// `FILEPROVIDE` strings -- which carry none (rpmlint `Pkg._gather_files`).
pub fn parse_dep_infos(line: &str) -> Vec<DepInfo> {
    fn plain(name: &str) -> DepInfo {
        DepInfo {
            name: name.to_string(),
            flags: 0,
            epoch: None,
            version: None,
            release: None,
        }
    }
    let mut tokens: Vec<&str> = split_dep_tokens(line);
    // Drop a trailing line-continuation backslash (pkg.py:310-311).
    if tokens.last().is_some_and(|t| *t == "\\") {
        tokens.pop();
    }
    let mut out = Vec::new();
    // The reference accumulates `prco` as [name], [name, flags],
    // [name, flags, evr].
    let mut pending: Option<(&str, u32)> = None;
    for token in tokens {
        if token.is_empty() {
            continue;
        }
        match pending.take() {
            None => pending = Some((token, 0)),
            Some((name, 0)) => {
                if let Some(flags) = dep_op_flags(token) {
                    pending = Some((name, flags));
                } else {
                    out.push(plain(name));
                    pending = Some((token, 0));
                }
            }
            Some((name, flags)) => {
                let (epoch, version, release) = string_to_version(token);
                out.push(DepInfo {
                    name: name.to_string(),
                    flags,
                    epoch,
                    version,
                    release,
                });
            }
        }
    }
    match pending {
        // A dangling version operator (`Requires: foo >=`): versioned, but
        // the version token is missing.
        Some((name, flags)) if flags != 0 => out.push(DepInfo {
            name: name.to_string(),
            flags,
            epoch: None,
            version: None,
            release: None,
        }),
        Some((name, _)) => out.push(plain(name)),
        None => {}
    }
    out
}

/// Version-operator flags for a dep-line token, mirroring the reference's
/// `parse_deps` operator detection: a leading `=`/`<`/`>` marks an operator,
/// and each operator character present contributes its `RPMSENSE_*` bit.
fn dep_op_flags(token: &str) -> Option<u32> {
    if !token.starts_with(['=', '<', '>']) {
        return None;
    }
    let mut flags = 0;
    if token.contains('=') {
        flags |= RPMSENSE_EQUAL;
    }
    if token.contains('<') {
        flags |= RPMSENSE_LESS;
    }
    if token.contains('>') {
        flags |= RPMSENSE_GREATER;
    }
    Some(flags)
}

/// `rpmlint.pkg.has_forbidden_controlchars` on a string: the string itself
/// when it holds a control character other than tab, LF or CR, else `None`.
pub fn has_forbidden_controlchars(s: &str) -> Option<String> {
    if s.bytes().any(|c| c < 32 && c != 9 && c != 10 && c != 13) {
        Some(s.to_string())
    } else {
        None
    }
}

/// `has_forbidden_controlchars` on a `parse_deps` list. The reference recurses
/// into the list but returns after the first item, so only the first dep's
/// name is ever examined; mirrored here so findings stay identical.
pub fn has_forbidden_controlchars_deps(deps: &[(String, Option<String>)]) -> Option<String> {
    deps.first()
        .and_then(|(name, _)| has_forbidden_controlchars(name))
}

/// A single plain dependency referenced inside a (possibly rich) dependency
/// expression: the bare name with its qualifier and version constraint.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DepLeaf {
    pub name: String,
    pub qualifier: Option<String>,
    pub flags: u32,
    pub epoch: Option<i64>,
    pub version: Option<String>,
    pub release: Option<String>,
}

impl DepLeaf {
    /// `name [<|>|= evr]`, mirroring `formatRequire` for one leaf.
    pub fn display(&self) -> String {
        let mut s = self.name.clone();
        if self.flags & (RPMSENSE_LESS | RPMSENSE_GREATER | RPMSENSE_EQUAL) != 0 {
            s.push(' ');
            if self.flags & RPMSENSE_LESS != 0 {
                s.push('<');
            }
            if self.flags & RPMSENSE_GREATER != 0 {
                s.push('>');
            }
            if self.flags & RPMSENSE_EQUAL != 0 {
                s.push('=');
            }
            s.push(' ');
            s.push_str(&version_to_string(
                self.epoch,
                self.version.as_deref(),
                self.release.as_deref(),
            ));
        }
        s
    }
}

/// Maximum nesting depth of a rich-dependency expression.
///
/// The parser recurses once per parenthesis level over a package-controlled
/// header string, so an unbounded expression (`((((...))))` in `REQUIRENAME`)
/// overflows the stack and aborts the process. Real-world rich dependencies
/// nest only a handful of levels; 64 is an order of magnitude beyond anything
/// legitimate and comfortably below the ~400-level overflow threshold measured
/// in a test thread. Past the budget the input falls back to `DepExpr::Simple { .. }` holding
/// the raw string.
///
/// At depth 65+ even a well-formed expression reads exactly like a parse error:
/// one opaque `DepExpr::Simple { .. }` leaf, and every leaf analysis goes dark.
///
/// The bound also caps the `Box` tree depth, so the drop glue
/// can never recurse into an overflow either.
const MAX_RICH_DEP_DEPTH: usize = 64;

/// A parsed RPM rich (boolean) dependency expression (rpm.org, RPM >= 4.13),
/// including RPM >= 4.16 dependency qualifiers (`foo(meta)`).
///
/// Malformed input parses to `DepExpr::Simple { .. }` holding the raw string, so a
/// parenthesized expression is never silently shredded into plain-name
/// tokens the way the reference's `parse_deps` shreds it.
///
/// This is not rpm's grammar: all six operators share one left-associative
/// loop, so `(a or b with c)` parses as `With([Or(a,b), c])` where rpm's
/// yacc grammar gives `Or([a, With(b,c)])`. rpm rejects mixed-operator
/// chains outright (`error: Cannot chain different ops`), so the shape is
/// unreachable from any rpm-built package, and no consumer inspects tree
/// shape -- only `leaves()` (a left-to-right flatten) and `is_rich()` are
/// read, both order-identical either way.

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DepExpr {
    Simple {
        name: String,
        qualifier: Option<String>,
        flags: u32,
        epoch: Option<i64>,
        version: Option<String>,
        release: Option<String>,
    },
    And(Vec<DepExpr>),
    Or(Vec<DepExpr>),
    If {
        cond: Box<DepExpr>,
        then: Box<DepExpr>,
    },
    Unless {
        cond: Box<DepExpr>,
        then: Box<DepExpr>,
    },
    With {
        lhs: Box<DepExpr>,
        rhs: Box<DepExpr>,
    },
    Without {
        lhs: Box<DepExpr>,
        rhs: Box<DepExpr>,
    },
}

impl DepExpr {
    /// All plain dependencies referenced, flattened left to right.
    ///
    /// Iterative over an explicit stack: the tree is built from a
    /// package-controlled string, so a recursive walk would reintroduce
    /// the stack exhaustion the parse budget guards against.
    pub fn leaves(&self) -> Vec<DepLeaf> {
        fn simple_leaf(
            name: &str,
            qualifier: &Option<String>,
            flags: u32,
            epoch: Option<i64>,
            version: &Option<String>,
            release: &Option<String>,
        ) -> DepLeaf {
            DepLeaf {
                name: name.to_string(),
                qualifier: qualifier.clone(),
                flags,
                epoch,
                version: version.clone(),
                release: release.clone(),
            }
        }
        let mut out = Vec::new();
        let mut stack: Vec<&DepExpr> = vec![self];
        while let Some(e) = stack.pop() {
            match e {
                DepExpr::Simple {
                    name,
                    qualifier,
                    flags,
                    epoch,
                    version,
                    release,
                } => out.push(simple_leaf(
                    name, qualifier, *flags, *epoch, version, release,
                )),
                // Push children reversed so the leftmost pops first;
                // `if`/`unless` list `then` before `cond`, preserving the
                // original recursive order.
                DepExpr::And(v) | DepExpr::Or(v) => stack.extend(v.iter().rev()),
                DepExpr::If { cond, then } | DepExpr::Unless { cond, then } => {
                    stack.push(cond);
                    stack.push(then);
                }
                DepExpr::With { lhs, rhs } | DepExpr::Without { lhs, rhs } => {
                    stack.push(rhs);
                    stack.push(lhs);
                }
            }
        }
        out
    }

    /// True for a well-formed boolean expression, as opposed to a plain
    /// (possibly qualified) name.
    pub fn is_rich(&self) -> bool {
        !matches!(self, DepExpr::Simple { .. })
    }
}

fn tokenize_rich(s: &str) -> Vec<String> {
    let mut toks = Vec::new();
    let mut cur = String::new();
    for c in s.chars() {
        if c == '(' || c == ')' {
            if !cur.is_empty() {
                toks.push(std::mem::take(&mut cur));
            }
            toks.push(c.to_string());
        } else if c.is_whitespace() {
            if !cur.is_empty() {
                toks.push(std::mem::take(&mut cur));
            }
        } else {
            cur.push(c);
        }
    }
    if !cur.is_empty() {
        toks.push(cur);
    }
    toks
}

fn is_bool_op(tok: &str) -> bool {
    matches!(tok, "and" | "or" | "if" | "unless" | "with" | "without")
}

fn version_op_flags(tok: &str) -> Option<u32> {
    // Mirrors rpmlint's parse_deps: any token starting with `=`, `<` or `>`
    // is a version operator, with flags from the characters present. This
    // accepts `=<` (old-style `<=`), `=>`, `==` etc., exactly like the
    // reference; without it rich expressions using `=<` fail to parse and
    // fall back to opaque names.
    if !tok.starts_with(['=', '<', '>']) {
        return None;
    }
    let mut flags = 0u32;
    if tok.contains('=') {
        flags |= RPMSENSE_EQUAL;
    }
    if tok.contains('<') {
        flags |= RPMSENSE_LESS;
    }
    if tok.contains('>') {
        flags |= RPMSENSE_GREATER;
    }
    Some(flags)
}

struct RichParser {
    toks: Vec<String>,
    pos: usize,
    depth: usize,
}

impl RichParser {
    fn peek(&self) -> Option<&str> {
        self.toks.get(self.pos).map(|s| s.as_str())
    }

    fn peek_at(&self, off: usize) -> Option<&str> {
        self.toks.get(self.pos + off).map(|s| s.as_str())
    }

    fn next(&mut self) -> Option<String> {
        let t = self.toks.get(self.pos).cloned();
        if t.is_some() {
            self.pos += 1;
        }
        t
    }

    /// `expr := term (op term)*`, left-associative; runs of `and`/`or`
    /// flatten into one n-ary node.
    fn parse_expr(&mut self) -> Result<DepExpr, ()> {
        let mut node = self.parse_term()?;
        loop {
            let op: &str = match self.peek() {
                Some("and") => "and",
                Some("or") => "or",
                Some("if") => "if",
                Some("unless") => "unless",
                Some("with") => "with",
                Some("without") => "without",
                _ => break,
            };
            self.pos += 1;
            let rhs = self.parse_term()?;
            node = match op {
                "and" => match node {
                    DepExpr::And(mut v) => {
                        v.push(rhs);
                        DepExpr::And(v)
                    }
                    _ => DepExpr::And(vec![node, rhs]),
                },
                "or" => match node {
                    DepExpr::Or(mut v) => {
                        v.push(rhs);
                        DepExpr::Or(v)
                    }
                    _ => DepExpr::Or(vec![node, rhs]),
                },
                "if" => DepExpr::If {
                    cond: Box::new(rhs),
                    then: Box::new(node),
                },
                "unless" => DepExpr::Unless {
                    cond: Box::new(rhs),
                    then: Box::new(node),
                },
                "with" => DepExpr::With {
                    lhs: Box::new(node),
                    rhs: Box::new(rhs),
                },
                _ => DepExpr::Without {
                    lhs: Box::new(node),
                    rhs: Box::new(rhs),
                },
            };
        }
        Ok(node)
    }

    fn parse_term(&mut self) -> Result<DepExpr, ()> {
        match self.peek() {
            Some("(") => {
                // One recursion per nesting level over package-controlled
                // input: cap the depth so a malicious header string cannot
                // overflow the stack. Past the budget the whole input
                // falls back to `DepExpr::Simple { .. }` holding the raw string.
                if self.depth >= MAX_RICH_DEP_DEPTH {
                    return Err(());
                }
                self.depth += 1;
                self.pos += 1;
                let e = self.parse_expr()?;
                self.depth -= 1;
                if self.peek() != Some(")") {
                    return Err(());
                }
                self.pos += 1;
                Ok(e)
            }
            Some(t) if is_bool_op(t) || t == ")" => Err(()),
            Some(_) => self.parse_simple(),
            None => Err(()),
        }
    }

    /// `name [(qualifier)] [op version]`
    fn parse_simple(&mut self) -> Result<DepExpr, ()> {
        let name = self.next().ok_or(())?;
        // A qualifier is `(word)` directly after the name (RPM >= 4.16,
        // e.g. `foo(meta)`); anything else parenthesized is not one.
        let mut qualifier = None;
        if self.peek() == Some("(")
            && self
                .peek_at(1)
                .is_some_and(|w| !is_bool_op(w) && w != "(" && w != ")")
            && self.peek_at(2) == Some(")")
        {
            self.pos += 1;
            qualifier = self.next();
            self.pos += 1; // consume ")"
        }
        let mut flags = 0u32;
        let mut epoch = None;
        let mut version = None;
        let mut release = None;
        if let Some(op) = self.peek().and_then(version_op_flags) {
            self.pos += 1;
            let v = self
                .next()
                .filter(|t| !is_bool_op(t) && t != "(" && t != ")")
                .ok_or(())?;
            flags = op;
            (epoch, version, release) = string_to_version(&v);
        }
        Ok(DepExpr::Simple {
            name,
            qualifier,
            flags,
            epoch,
            version,
            release,
        })
    }
}

/// Parse a dependency name into a rich-expression tree.
///
/// `(a or b)` and friends become structured nodes; a plain name (with an
/// optional RPM 4.16 `(qualifier)`) becomes `DepExpr::Simple { .. }`. Anything malformed
/// becomes `DepExpr::Simple { .. }` holding the raw string.
pub fn parse_dep_expr(s: &str) -> DepExpr {
    let raw = || DepExpr::Simple {
        name: s.to_string(),
        qualifier: None,
        flags: 0,
        epoch: None,
        version: None,
        release: None,
    };
    let toks = tokenize_rich(s);
    if toks.is_empty() {
        return raw();
    }
    let mut p = RichParser {
        toks,
        pos: 0,
        depth: 0,
    };
    // A bare name parses as `simple`; a leading `(` needs the full
    // expression grammar.
    let parsed = if p.peek() == Some("(") {
        p.parse_expr()
    } else {
        p.parse_simple()
    };
    match parsed {
        Ok(e) if p.pos == p.toks.len() => e,
        _ => raw(),
    }
}

/// True when `s` is a well-formed rich dependency expression.
///
/// Skips the tokenizing parse for strings without parens: the expression
/// grammar is only entered on a leading `(`, and `parse_simple` always
/// yields `Simple`, so a paren-less string can never be rich. The
/// load-bearing invariant is that `is_rich()` is `!matches!(self, DepExpr::Simple { .. })`
/// and parens around a single term collapse to `DepExpr::Simple { .. }`, so `(a)` and
/// `((((a))))` are not rich on either path -- which is what makes any
/// `(`-based guard safe. This lets the per-token guards in SpecCheck
/// skip the tokenizing parse for plain dependency names.
pub fn is_rich_dep_expr(s: &str) -> bool {
    s.contains('(') && parse_dep_expr(s).is_rich()
}

/// Whether `s` is a parenthesized token like `(clang >= 17)` whose inner
/// content, shredded the way the reference shreds it, is entirely versioned
/// dependencies.
///
/// Our `parse_deps` keeps `(…)` whole as one token while the reference splits
/// it on whitespace and only warns on unversioned names; a parenthesized
/// versioned dependency is a boolean expression per RPM grammar, so the
/// reference never warns on it. Without this guard the
/// `comparison-operator-in-deptoken` check false-positives on operators that
/// are legitimate boolean-expression syntax. Malformed tokens like `(foo<bar)`
/// still warn, exactly like the reference.
///
/// Only a single paren layer is unwrapped: `((a >= 1))` would need a
/// loop-strip, but double-wrapped tokens cannot arise from real spec
/// dependency lists, so they are left to warn.
pub fn is_parenthesized_versioned(s: &str) -> bool {
    let Some(inner) = s.strip_prefix('(').and_then(|t| t.strip_suffix(')')) else {
        return false;
    };
    let deps = parse_deps(inner);
    !deps.is_empty() && deps.iter().all(|(_, version)| version.is_some())
}

#[cfg(test)]
mod parse_deps_tests {
    use super::*;

    #[test]
    fn plain_names_are_unversioned() {
        assert_eq!(
            parse_deps("foo bar"),
            vec![("foo".to_string(), None), ("bar".to_string(), None),]
        );
    }

    #[test]
    fn versioned_dep_keeps_its_version() {
        assert_eq!(
            parse_deps("foo >= 1.0, bar"),
            vec![
                ("foo".to_string(), Some("1.0".to_string())),
                ("bar".to_string(), None),
            ]
        );
    }

    #[test]
    fn trailing_backslash_is_dropped() {
        assert_eq!(
            parse_deps("foo bar \\"),
            vec![("foo".to_string(), None), ("bar".to_string(), None),]
        );
    }

    #[test]
    fn dangling_operator_is_versioned_without_version() {
        // `Requires: foo >=`: the reference sets flags but no EVR, so
        // `unversioned` (flags == 0) does not yield it.
        assert_eq!(
            parse_deps("foo >="),
            vec![("foo".to_string(), Some(String::new()))]
        );
    }

    #[test]
    fn empty_line_parses_to_nothing() {
        assert!(parse_deps("").is_empty());
        assert!(parse_deps("   ").is_empty());
    }

    #[test]
    fn dep_infos_plain_names_are_unversioned() {
        let deps = parse_dep_infos("foo bar");
        assert_eq!(deps.len(), 2);
        assert_eq!(deps[0].name, "foo");
        assert_eq!(deps[0].flags, 0);
        assert_eq!(
            (
                deps[0].epoch,
                deps[0].version.clone(),
                deps[0].release.clone()
            ),
            (None, None, None)
        );
        assert_eq!(deps[1].name, "bar");
    }

    #[test]
    fn dep_infos_versioned_dep_carries_flags_and_evr() {
        let deps = parse_dep_infos("foo >= 1.0-2");
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "foo");
        assert_eq!(deps[0].flags, RPMSENSE_GREATER | RPMSENSE_EQUAL);
        assert_eq!(deps[0].epoch, None);
        assert_eq!(deps[0].version.as_deref(), Some("1.0"));
        assert_eq!(deps[0].release.as_deref(), Some("2"));
    }

    #[test]
    fn dep_infos_epoch_parsed() {
        let deps = parse_dep_infos("foo = 1:2.0-3");
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].flags, RPMSENSE_EQUAL);
        assert_eq!(deps[0].epoch, Some(1));
        assert_eq!(deps[0].version.as_deref(), Some("2.0"));
        assert_eq!(deps[0].release.as_deref(), Some("3"));
    }

    #[test]
    fn dep_infos_comma_separated() {
        let deps = parse_dep_infos("foo, bar < 2.0");
        assert_eq!(deps.len(), 2);
        assert_eq!(deps[0].name, "foo");
        assert_eq!(deps[0].flags, 0);
        assert_eq!(deps[1].name, "bar");
        assert_eq!(deps[1].flags, RPMSENSE_LESS);
        assert_eq!(deps[1].version.as_deref(), Some("2.0"));
    }

    #[test]
    fn dep_infos_dangling_operator_is_versioned_without_evr() {
        let deps = parse_dep_infos("foo >=");
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "foo");
        assert_eq!(deps[0].flags, RPMSENSE_GREATER | RPMSENSE_EQUAL);
        assert_eq!(deps[0].version, None);
    }

    #[test]
    fn dep_infos_empty_line_parses_to_nothing() {
        assert!(parse_dep_infos("").is_empty());
        assert!(parse_dep_infos("   ").is_empty());
    }

    #[test]
    fn dep_infos_per_file_require_shape() {
        // The NsCDE-doc shape: a bare path require.
        let deps = parse_dep_infos("/bin/ksh");
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "/bin/ksh");
        assert_eq!(deps[0].flags, 0);
    }

    #[test]
    fn controlchars_found_in_string() {
        assert_eq!(
            has_forbidden_controlchars("a\x01b"),
            Some("a\x01b".to_string())
        );
        assert_eq!(has_forbidden_controlchars("a\tb\nc\rd"), None);
        assert_eq!(has_forbidden_controlchars("plain"), None);
    }

    #[test]
    fn controlchars_in_deps_only_look_at_the_first_name() {
        // Mirrors the reference's return-after-first-item: the bad second
        // dep is not reported.
        let deps = vec![("foo".to_string(), None), ("b\x01ar".to_string(), None)];
        assert_eq!(has_forbidden_controlchars_deps(&deps), None);
        let deps = vec![("f\x01oo".to_string(), None)];
        assert_eq!(
            has_forbidden_controlchars_deps(&deps),
            Some("f\x01oo".to_string())
        );
        let empty: Vec<(String, Option<String>)> = Vec::new();
        assert_eq!(has_forbidden_controlchars_deps(&empty), None);
    }
}

#[cfg(test)]
mod rich_dep_depth_tests {
    use super::*;

    fn nested_parens(depth: usize) -> String {
        format!("{}a{}", "(".repeat(depth), ")".repeat(depth))
    }

    #[test]
    fn deep_nesting_falls_back_to_raw_without_crashing() {
        // Regression: a package-controlled header string with thousands of
        // nested parens overflowed the parser stack and aborted the process
        // (SIGABRT). Past the depth budget the input degrades to `DepExpr::Simple { .. }`
        // holding the raw string.
        let s = nested_parens(2000);
        let parsed = parse_dep_expr(&s);
        assert!(!parsed.is_rich());
        assert_eq!(
            parsed,
            DepExpr::Simple {
                name: s.clone(),
                qualifier: None,
                flags: 0,
                epoch: None,
                version: None,
                release: None,
            }
        );
        // The fallback is also what `leaves()` sees: one leaf, raw name.
        let dep = DepInfo {
            name: s.clone(),
            flags: 0,
            epoch: None,
            version: None,
            release: None,
        };
        let leaves = dep.leaves();
        assert_eq!(leaves.len(), 1);
        assert_eq!(leaves[0].name, s);
    }

    #[test]
    fn over_budget_nesting_falls_back_to_raw() {
        let s = nested_parens(MAX_RICH_DEP_DEPTH + 36);
        assert!(!parse_dep_expr(&s).is_rich());
    }

    #[test]
    fn at_budget_nesting_still_parses() {
        // The budget itself is usable depth; only past it degrades.
        // (Bare parens around a name are not a rich expression, so nest
        // real `or`s to probe the boundary.)
        let mut s = String::from("a0");
        for i in 1..=MAX_RICH_DEP_DEPTH {
            s = format!("(a{i} or {s})");
        }
        assert!(parse_dep_expr(&s).is_rich());
        let mut s = String::from("a0");
        for i in 1..=MAX_RICH_DEP_DEPTH + 1 {
            s = format!("(a{i} or {s})");
        }
        assert!(!parse_dep_expr(&s).is_rich());
    }

    #[test]
    fn leaves_is_iterative_on_deep_tree() {
        // A 1000-deep tree would overflow a recursive walk (the test-thread
        // threshold is ~400-500); the iterative walk flattens it left to
        // right. The tree is forgotten, not dropped: the test only proves
        // the walk is iterative, and a recursive drop would abort.
        let mut tree = DepExpr::Simple {
            name: "leaf0".to_string(),
            qualifier: None,
            flags: 0,
            epoch: None,
            version: None,
            release: None,
        };
        for i in 1..1000usize {
            tree = DepExpr::Or(vec![
                DepExpr::Simple {
                    name: format!("leaf{i}"),
                    qualifier: None,
                    flags: 0,
                    epoch: None,
                    version: None,
                    release: None,
                },
                tree,
            ]);
        }
        let names: Vec<String> = tree.leaves().into_iter().map(|l| l.name).collect();
        assert_eq!(names.len(), 1000);
        assert_eq!(names[0], "leaf999");
        assert_eq!(names[999], "leaf0");
        std::mem::forget(tree);
    }

    #[test]
    fn deep_but_in_budget_parses_and_flattens() {
        // 60 nested `or`s: within budget, parses rich, flattens in order.
        let mut s = String::from("a0");
        for i in 1..60usize {
            s = format!("(a{i} or {s})");
        }
        let parsed = parse_dep_expr(&s);
        assert!(parsed.is_rich());
        let names: Vec<String> = parsed.leaves().into_iter().map(|l| l.name).collect();
        assert_eq!(names.len(), 60);
        assert_eq!(names[0], "a59");
        assert_eq!(names[59], "a0");
    }
}

#[cfg(test)]
mod rich_dep_tests {
    use super::*;

    fn simple(name: &str) -> DepExpr {
        DepExpr::Simple {
            name: name.to_string(),
            qualifier: None,
            flags: 0,
            epoch: None,
            version: None,
            release: None,
        }
    }

    fn ver(name: &str, flags: u32, version: &str) -> DepExpr {
        DepExpr::Simple {
            name: name.to_string(),
            qualifier: None,
            flags,
            epoch: None,
            version: Some(version.to_string()),
            release: None,
        }
    }

    #[test]
    fn plain_name_stays_simple() {
        assert_eq!(parse_dep_expr("foo"), simple("foo"));
        assert_eq!(parse_dep_expr("foo-1.2"), simple("foo-1.2"));
        assert!(!is_rich_dep_expr("foo"));
    }

    #[test]
    fn version_op_flags_accepts_old_style_operators() {
        // `=<` is old-style `<=`; the reference treats any token starting
        // with `=`, `<`, `>` as a version operator (#362).
        assert_eq!(version_op_flags("=<"), Some(RPMSENSE_LESS | RPMSENSE_EQUAL));
        assert_eq!(
            version_op_flags("=>"),
            Some(RPMSENSE_GREATER | RPMSENSE_EQUAL)
        );
        assert_eq!(version_op_flags("=="), Some(RPMSENSE_EQUAL));
        assert_eq!(
            version_op_flags(">="),
            Some(RPMSENSE_GREATER | RPMSENSE_EQUAL)
        );
        assert!(version_op_flags("foo").is_none());
        assert!(version_op_flags("").is_none());
    }

    #[test]
    fn parenthesized_versioned_dep_is_detected() {
        assert!(is_parenthesized_versioned("(clang >= 17)"));
        assert!(is_parenthesized_versioned("(cmake(Clang) >= 1.0)"));
        assert!(is_parenthesized_versioned("(a =< b)"));
        assert!(!is_parenthesized_versioned("(foo<bar)"));
        assert!(!is_parenthesized_versioned("(foo)"));
        assert!(!is_parenthesized_versioned("foo"));
        assert!(!is_parenthesized_versioned("(foo"));
        assert!(!is_parenthesized_versioned(""));
        // Boolean operators make it rich, not parenthesized-versioned;
        // is_rich_dep_expr covers those.
        assert!(!is_parenthesized_versioned("(a or b)"));
    }

    #[test]
    fn rich_dep_with_old_style_operator_parses() {
        // #362: `=<` inside a rich expression must parse, not fall back to
        // an opaque name.
        assert!(parse_dep_expr("(a >= 1.0 with b =< 2.0)").is_rich());
    }

    #[test]
    fn rich_check_agrees_with_full_parse() {
        // The paren short-circuit in `is_rich_dep_expr` must never
        // diverge from the tokenizing parse it skips.
        for s in [
            "",
            " ",
            "   ",
            ",,,",
            "a, b, c",
            "foo",
            "foo >= 1.0",
            "foo(bar)",
            "libc.so.6()(64bit)",
            "(foo)",
            "(a or b)",
            "(a >= 1.0 with b < 2.0)",
            "((a))",
            "(a",
            "a)",
            "()",
        ] {
            assert_eq!(is_rich_dep_expr(s), parse_dep_expr(s).is_rich(), "{s:?}");
        }
    }

    #[test]
    fn qualifier_is_parsed_but_name_stays_whole() {
        // RPM >= 4.16 dependency qualifier (#429).
        assert_eq!(
            parse_dep_expr("qux(meta)"),
            DepExpr::Simple {
                name: "qux".to_string(),
                qualifier: Some("meta".to_string()),
                flags: 0,
                epoch: None,
                version: None,
                release: None,
            }
        );
        let dep = DepInfo {
            name: "qux(meta)".to_string(),
            flags: 0,
            epoch: None,
            version: None,
            release: None,
        };
        // Like the reference, analyses match the literal name; the
        // qualifier is only additionally structured. Stripping would mangle
        // real capability names such as `rpmlib(CompressedFileNames)`.
        assert_eq!(dep.leaf_names(), vec!["qux(meta)".to_string()]);
        assert_eq!(dep.leaves()[0].qualifier.as_deref(), Some("meta"));
    }

    #[test]
    fn or_expression() {
        assert_eq!(
            parse_dep_expr("(foo or bar)"),
            DepExpr::Or(vec![simple("foo"), simple("bar")])
        );
    }

    #[test]
    fn and_flattens() {
        assert_eq!(
            parse_dep_expr("(a and b and c)"),
            DepExpr::And(vec![simple("a"), simple("b"), simple("c")])
        );
    }

    #[test]
    fn nested_expression() {
        assert_eq!(
            parse_dep_expr("(outer and (inner1 or inner2))"),
            DepExpr::And(vec![
                simple("outer"),
                DepExpr::Or(vec![simple("inner1"), simple("inner2")]),
            ])
        );
    }

    #[test]
    fn if_unless_with_without() {
        assert_eq!(
            parse_dep_expr("(a if b)"),
            DepExpr::If {
                cond: Box::new(simple("b")),
                then: Box::new(simple("a")),
            }
        );
        assert_eq!(
            parse_dep_expr("(a unless b)"),
            DepExpr::Unless {
                cond: Box::new(simple("b")),
                then: Box::new(simple("a")),
            }
        );
        assert_eq!(
            parse_dep_expr("(a with b)"),
            DepExpr::With {
                lhs: Box::new(simple("a")),
                rhs: Box::new(simple("b")),
            }
        );
        assert_eq!(
            parse_dep_expr("(a without b)"),
            DepExpr::Without {
                lhs: Box::new(simple("a")),
                rhs: Box::new(simple("b")),
            }
        );
    }

    #[test]
    fn versioned_terms_inside_expression() {
        // `(baz >= 1.0 with baz < 2.0)`: the canonical rpm.org example.
        assert_eq!(
            parse_dep_expr("(baz >= 1.0 with baz < 2.0)"),
            DepExpr::With {
                lhs: Box::new(ver("baz", RPMSENSE_GREATER | RPMSENSE_EQUAL, "1.0")),
                rhs: Box::new(ver("baz", RPMSENSE_LESS, "2.0")),
            }
        );
    }

    #[test]
    fn malformed_input_falls_back_to_raw_name() {
        for bad in ["(foo or", "(foo or)", "()", "( and b)", "foo bar", ""] {
            let expr = parse_dep_expr(bad);
            assert_eq!(
                expr,
                DepExpr::Simple {
                    name: bad.to_string(),
                    qualifier: None,
                    flags: 0,
                    epoch: None,
                    version: None,
                    release: None,
                },
                "input: {bad:?}"
            );
            assert!(!expr.is_rich());
        }
    }

    #[test]
    fn leaves_flatten_in_order() {
        let expr = parse_dep_expr("(outer and (inner1 or inner2))");
        let names: Vec<String> = expr.leaves().iter().map(|l| l.name.clone()).collect();
        assert_eq!(names, vec!["outer", "inner1", "inner2"]);
    }

    #[test]
    fn dep_info_leaves_carry_header_evr_for_plain_names() {
        let dep = DepInfo {
            name: "foo".to_string(),
            flags: RPMSENSE_EQUAL,
            epoch: None,
            version: Some("1.0".to_string()),
            release: Some("2".to_string()),
        };
        let leaves = dep.leaves();
        assert_eq!(leaves.len(), 1);
        assert_eq!(leaves[0].name, "foo");
        assert_eq!(leaves[0].flags, RPMSENSE_EQUAL);
        assert_eq!(leaves[0].display(), "foo = 1.0-2");
    }

    #[test]
    fn rich_dep_leaves_use_inner_constraints() {
        let dep = DepInfo {
            name: "(relfoo = 1.0-2 or relbar)".to_string(),
            flags: 0,
            epoch: None,
            version: None,
            release: None,
        };
        let leaves = dep.leaves();
        assert_eq!(leaves.len(), 2);
        assert_eq!(leaves[0].display(), "relfoo = 1.0-2");
        assert_eq!(leaves[0].flags, RPMSENSE_EQUAL);
        assert_eq!(leaves[0].release.as_deref(), Some("2"));
        assert_eq!(leaves[1].name, "relbar");
    }

    #[test]
    fn parse_deps_keeps_parenthesized_expression_whole() {
        // The reference shreds `(foo or bar)` into `(foo`/`or`/`bar)`;
        // the port keeps it as one token.
        assert_eq!(
            parse_deps("(foo or bar)"),
            vec![("(foo or bar)".to_string(), None)]
        );
        assert_eq!(
            parse_deps("plain, (a or b), other >= 1.0"),
            vec![
                ("plain".to_string(), None),
                ("(a or b)".to_string(), None),
                ("other".to_string(), Some("1.0".to_string())),
            ]
        );
    }

    #[test]
    fn first_dep_token_matches_full_tokenizer() {
        // The manual first-token scan must return exactly the token the full
        // `split_dep_tokens` tokenizer would yield first, on every line shape.
        let lines = [
            "",
            "   ",
            "foo",
            "  foo  ",
            "foo >= 1.2",
            "foo,bar",
            "foo, bar, baz",
            "foo,",
            ",foo",
            "(a or b)",
            "  (a or b) >= 2.0",
            "(a or b), (c and d)",
            "(a (b or c))",
            "(unbalanced",
            "unbalanced)",
            "()",
            "(a or b)trailing",
            "libfoo.so.1()(64bit) >= 2.0, other",
            "name-with-dash_and.dot:plus~tilde",
            "tab\tseparated",
        ];
        for line in lines {
            assert_eq!(
                first_dep_token(line),
                split_dep_tokens(line).into_iter().next(),
                "line: {line:?}"
            );
        }
    }
}
