#!/usr/bin/env python3
"""Regenerate crates/rpmcrab-core/tests/data/reference-checks.txt.

Derives the reference check set from the pinned rpmlint tree the way
rpmlint's own loader resolves a check (lint.py: load_check): each
rpmlint/checks/<Name>.py module that defines a class named <Name> is a
check, because the loader does ``getattr(module, name)``. Two modules are
not checks and are excluded:

- AbstractCheck.py only holds the base classes (never instantiated as a
  check by any shipped config);
- TmpfilesParser.py holds a parser helper and defines no same-named class,
  so the loader could not resolve it either.

Usage:
    scripts/gen-reference-checks.py [REF_DIR]

REF_DIR is the reference rpmlint checkout and defaults to the
scripts/setup-rpmlint-ref.sh layout (.parity-ref/rpmlint-src). Regenerate
whenever the reference is re-pinned (REF_SHA in setup-rpmlint-ref.sh);
the generated file records the commit it was derived from.
"""

import ast
import os
import subprocess
import sys


def is_check(module_path, module_name):
    """A module is a check iff it defines a class with its own name, and it
    is not the module holding the abstract base classes."""
    if module_name == "AbstractCheck":
        return False
    with open(module_path, encoding="utf-8") as f:
        tree = ast.parse(f.read(), module_path)
    return any(
        isinstance(node, ast.ClassDef) and node.name == module_name
        for node in tree.body
    )


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ref_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        repo_root, ".parity-ref", "rpmlint-src"
    )
    checks_dir = os.path.join(ref_dir, "rpmlint", "checks")
    if not os.path.isdir(checks_dir):
        sys.exit(f"not a reference checkout: {checks_dir} missing")

    names = sorted(
        fname[:-3]
        for fname in os.listdir(checks_dir)
        if fname.endswith(".py")
        and is_check(os.path.join(checks_dir, fname), fname[:-3])
    )

    try:
        sha = subprocess.run(
            ["git", "-C", ref_dir, "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        sha = "unknown"

    out_path = os.path.join(
        repo_root, "crates", "rpmcrab-core", "tests", "data",
        "reference-checks.txt",
    )
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "# Reference rpmlint check modules, one per line, derived from the\n"
            "# pinned reference tree (rpmlint/checks/*.py -> class names, the\n"
            "# way lint.py:load_check resolves them; AbstractCheck.py and\n"
            "# TmpfilesParser.py are not checks and are excluded).\n"
            f"# Generated by scripts/gen-reference-checks.py from reference commit {sha}.\n"
            "# Regenerate when the reference is re-pinned:\n"
            "#     scripts/gen-reference-checks.py /path/to/rpmlint\n"
            "# (the scripts/setup-rpmlint-ref.sh checkout at .parity-ref/rpmlint-src works).\n"
        )
        for name in names:
            f.write(name + "\n")
    print(f"wrote {out_path} ({len(names)} checks, ref {sha})")


if __name__ == "__main__":
    main()
